[workspace]
members = [
    "inox-core",
    "inox-gtk"
#    "inox-tui"
]

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false

[patch."https://github.com/gtk-rs/gtk.git"]
gtk = { path="../gtk-rs" }