[package]
name = "Inox"
version = "0.0.1"
authors = ["Dirk Van Haerenborgh <vhdirk@gmail.com>"]

[lib]
name = "inox_core"
path = "src/core/lib.rs"

[[bin]]
name = "inox-gtk"
path = "src/gtk/main.rs"


[dependencies]
structopt = "0.2"
log = "*"
env_logger ="*"
shellexpand = "*"
net2 = "*"
nix = "*"
regex = "*"
toml = "*"
serde = "*"
serde_derive = "*"
serde_ini = "*"
lazy_static = "1.0"
vte = "0.3.2"
chrono = { version = "0.4", features = ["serde"] }
notmuch = "*"

glib-sys = { git = "https://github.com/gtk-rs/sys" }
gobject-sys = { git = "https://github.com/gtk-rs/sys" }
gio-sys = { git = "https://github.com/gtk-rs/sys" }
gdk-sys = { git = "https://github.com/gtk-rs/sys" }
gdk-pixbuf-sys = { git = "https://github.com/gtk-rs/sys" }
gtk-sys = { git = "https://github.com/gtk-rs/sys" }
cairo-sys-rs = { git = "https://github.com/gtk-rs/cairo" }

glib = { git = "https://github.com/gtk-rs/glib" }
gio = { git = "https://github.com/gtk-rs/gio" }
gtk = { git = "https://github.com/gtk-rs/gtk" }
gdk = { git = "https://github.com/gtk-rs/gdk" }
gdk-pixbuf = { git = "https://github.com/gtk-rs/gdk-pixbuf" }
pango = { git = "https://github.com/gtk-rs/pango" }
cairo-rs = { git = "https://github.com/gtk-rs/cairo" }

gmime = { git = "https://github.com/vhdirk/gmime-rs" }

gobject-subclass = { git = "https://github.com/vhdirk/gst-plugin-rs" }

relm = { git = "https://github.com/vhdirk/relm" }
relm-derive = { git = "https://github.com/vhdirk/relm" }
relm-attributes = { git = "https://github.com/vhdirk/relm" }

# lettre = "*"
#
[replace]
"gobject-sys:0.6.0" = { git = "https://github.com/gtk-rs/sys" }
"glib-sys:0.6.0" = { git = "https://github.com/gtk-rs/sys" }
"gtk-sys:0.6.0" = { git = "https://github.com/gtk-rs/sys" }
"glib:0.5.0" = { git = "https://github.com/gtk-rs/glib" }
"gtk:0.4.0" = { git = "https://github.com/gtk-rs/gtk" }



[features]
default = ["gtk/v3_16", "relm/unstable", "relm-attributes/unstable", "relm-derive/unstable"]
gtk_3_10 = ["gtk/v3_10"]
gtk_3_16 = ["gtk_3_10", "gtk/v3_16"]
gtk_3_18 = ["gtk_3_16", "gtk/v3_18"] #for CI tools
gtk_3_20 = ["gtk_3_18", "gtk/v3_20"] #for CI tools

# [patch.crates-io]
# notmuch = { path="../notmuch-rs", optional = true }

[dev-dependencies]
cargo-expand = "*"
