[package]
name = "Inox"
version = "0.0.1"
authors = ["Dirk Van Haerenborgh <vhdirk@gmail.com>"]

[lib]
name = "inox_core"
path = "src/core/lib.rs"

[[bin]]
name = "inox-gtk"
path = "src/gtk/main.rs"


[dependencies]
structopt = "0.2"
log = "*"
env_logger ="*"
shellexpand = "*"
net2 = "*"
nix = "*"
regex = "*"
toml = "*"
serde = "*"
serde_derive = "*"
serde_ini = "*"
lazy_static = "1.0"
vte = "0.3.2"
chrono = { version = "0.4", features = ["serde"] }
notmuch = "*"

gtk        = "^0.4.0"
cairo-rs   = "^0.4.1"
pango      = "^0.4.0"
gdk        = "^0.8.0"
gdk-pixbuf = "^0.4.0"
gio        = "^0.4.0"
glib       = "^0.5.0"
pangocairo = "^0.5.0"
glib-sys       = "^0.6.0"
gobject-sys    = "^0.6.0"
gtk-sys        = "^0.6.0"
gdk-sys        = "^0.6.0"
gdk-pixbuf-sys = "^0.6.0"
cairo-sys-rs   = "^0.6.0"

gobject-subclass = "^0.1.0"
gmime       = "*"

relm = "^0.14.0"
relm-derive = "^0.14.0"
relm-attributes = "^0.14.0"





[features]
default = ["gtk/v3_16", "relm/unstable", "relm-attributes/unstable", "relm-derive/unstable"]
gtk_3_10 = ["gtk/v3_10"]
gtk_3_16 = ["gtk_3_10", "gtk/v3_16"]
gtk_3_18 = ["gtk_3_16", "gtk/v3_18"] #for CI tools
gtk_3_20 = ["gtk_3_18", "gtk/v3_20"] #for CI tools

# [patch.crates-io]
# notmuch = { path="../notmuch-rs", optional = true }

[dev-dependencies]
cargo-expand = "*"
