[package]
name = "Inox"
version = "0.0.1"
authors = ["Dirk Van Haerenborgh <vhdirk@gmail.com>"]

[lib]
name = "inox_core"
path = "src/core/lib.rs"

[[bin]]
name = "inox-gtk"
path = "src/gtk/main.rs"


[dependencies]
structopt = "0.2"
log = "*"
env_logger ="*"
shellexpand = "*"
net2 = "*"
nix = "*"
regex = "*"
toml = "*"
serde = "*"
serde_derive = "*"
serde_ini = "*"
lazy_static = "1.0"
vte = "0.3.2"
chrono = { version = "0.4", features = ["serde"] }
notmuch = "*"

gtk        = "^0.4.0"
cairo-rs   = "^0.4.1"
pango      = "^0.4.0"
gdk        = "^0.8.0"
gdk-pixbuf = "^0.4.0"
gio        = "^0.4.0"
glib       = "^0.5.0"
pangocairo = "^0.5.0"
glib-sys       = "^0.6.0"
gobject-sys    = "^0.6.0"
gtk-sys        = "^0.6.0"
gdk-sys        = "^0.6.0"
gdk-pixbuf-sys = "^0.6.0"
cairo-sys-rs   = "^0.6.0"
webkit2gtk     = "^0.4.0"
webkit2gtk-webextension = "^0.6.0"

gobject-subclass = "^0.1.0"
gmime       = "*"

relm = "^0.14.0"
relm-derive = "^0.14.0"
relm-attributes = "^0.14.0"

md5 = "0.3.7"



[features]
default = ["gtk/v3_16",
           "webkit2gtk/v2_16",
           "relm/unstable",
           "relm-attributes/unstable",
           "relm-derive/unstable"]


[patch.crates-io]
notmuch = { path="../notmuch-rs" }
gobject-subclass = { git = "https://github.com/sdroege/gobject-subclass" }
gmime = { path = "../gmime-rs" }

gtk = { git = "https://github.com/gtk-rs/gtk", branch="crate"}
cairo-rs = { git = "https://github.com/gtk-rs/cairo", branch="crate"}
pango = { git = "https://github.com/gtk-rs/pango", branch="crate"}
gdk = { git = "https://github.com/gtk-rs/gdk", branch="crate"}
gdk-pixbuf = { git = "https://github.com/gtk-rs/gdk-pixbuf", branch="crate"}
gio = { git = "https://github.com/gtk-rs/gio", branch="crate"}
glib = { git = "https://github.com/gtk-rs/glib", branch="crate"}
pangocairo = { git = "https://github.com/gtk-rs/pangocairo", branch="crate"}
glib-sys = { git = "https://github.com/gtk-rs/sys", branch="crate"}
gio-sys = { git = "https://github.com/gtk-rs/sys", branch="crate"}
gobject-sys = { git = "https://github.com/gtk-rs/sys", branch="crate"}
gtk-sys = { git = "https://github.com/gtk-rs/sys", branch="crate"}
gdk-sys = { git = "https://github.com/gtk-rs/sys", branch="crate"}
gdk-pixbuf-sys = { git = "https://github.com/gtk-rs/sys", branch="crate"}
cairo-sys-rs = { git = "https://github.com/gtk-rs/cairo", branch="crate"}


[dev-dependencies]
cargo-expand = "*"
