[package]
name = "inox-gtk"
version = "0.0.1"
authors = ["Dirk Van Haerenborgh <vhdirk@gmail.com>"]
build = "build.rs"
workspace = "../"
default-run = "inox-gtk"
edition = "2018"

[[bin]]
name = "inox-gtk"
path = "src/main.rs"

[lib]
path = "src/webextension/lib.rs"
name = "inox_gtk_webext"
crate-type = ["cdylib"]

[dependencies]
structopt = "0.2"
log = "*"
env_logger ="*"
pretty_env_logger = "0.4.0"
shellexpand = "*"
net2 = "*"
libc = "*"
nix = "*"
regex = "*"
toml = "*"
serde = "*"
serde_derive = "*"
serde_ini = "*"
lazy_static = "1.0"
vte = "0.3.2"
supercow = "0.1.0"
dirs = "1.0.4"
bincode = "1.0.1"
bytes = { version = "0.4.12", features = ["serde"] }
uuid = { version = "0.7", features = ["v4"] }
fragile = "0.3.0"
futures = "0.3"
async-std = "*"

chrono = { version = "0.4", features = ["serde"] }

gtk = { git = "https://github.com/gtk-rs/gtk", features=["v3_16"]}
cairo-rs = { git = "https://github.com/gtk-rs/cairo" }
pango = { git = "https://github.com/gtk-rs/pango" }
gdk = { git = "https://github.com/gtk-rs/gdk" }
gdk-pixbuf = { git = "https://github.com/gtk-rs/gdk-pixbuf" }
gio = { git = "https://github.com/gtk-rs/gio"}
glib = { git = "https://github.com/gtk-rs/glib" }
pangocairo = { git = "https://github.com/gtk-rs/pangocairo" }
glib-sys = { git = "https://github.com/gtk-rs/sys" }
gio-sys = { git = "https://github.com/gtk-rs/sys" }
gobject-sys = { git = "https://github.com/gtk-rs/sys" }
gtk-sys = { git = "https://github.com/gtk-rs/sys" }
gdk-sys = { git = "https://github.com/gtk-rs/sys" }
gdk-pixbuf-sys = { git = "https://github.com/gtk-rs/sys" }
cairo-sys-rs = { git = "https://github.com/gtk-rs/cairo" }
webkit2gtk = { git = "https://github.com/gtk-rs/webkit2gtk-rs", features=["v2_18"] }
webkit2gtk-webextension = { git = "https://github.com/gtk-rs/webkit2gtk-webextension-rs", features=["v2_18"] }

tarpc = { version = "0.20.0", path="../../tarpc/tarpc", features = ["serde1", "serde-transport", "tcp"] }
tokio = { version = "0.2", features = ["time"] }
tokio-serde = { version = "0.6", features = ["bincode", "json"] }
tokio-util = { version = "0.3", features = ["compat"] }
humantime = "1.0"
fnv = "1.0"
pin-project = "0.4"

crossbeam-channel = "0.2.1"
rayon = "1.0.1"
send-cell = "0.1.3"
failure = "0.1.1"
failure_derive = "0.1.1"
md5 = "0.3.7"

notmuch = "*"
gmime = { git = "https://github.com/vhdirk/gmime-rs"}

inox-core = { path = "../inox-core" }


[features]
default = ["gtk/v3_16"]

[dev-dependencies]
cargo-expand = "*"
pretty_assertions = "0.5.1"
